### ISSUE TITLE
Support regex matcher

### ISSUE THREAD

**Issue by SiAdcock** [courtroom/courtroom#38]
Something like:

```javascript
c.trial('email').laws.matches(/[A-Za-z_\.]+\@[A-Za-z_\.]+\.\w+/g);
```

**Comment by Jameskmonger** [comment]
I like it! I don't think it'd be particularly hard to implement. I'll pick this up at lunchtime! :smile:

**Comment by SiAdcock** [comment]
It is a great idea., but you might want to hold off on this for now. It was suggested to me by @AgentAntelope who said he'd raise a PR to implement.

**Comment by Jameskmonger** [comment]
Sounds good to me, @SiAdcock ! I've unassigned myself

**Comment by Jameskmonger** [comment]
I'd like to get this implemented for [v0.8](https://github.com/courtroom/courtroom/milestones/Courtroom%20v0.8). @SiAdcock, do you know how @AgentAntelope is getting on with it?

**Comment by SiAdcock** [comment]
Good question, I have not heard from him since he forked it. I'll check tomorrow and get back to you

**Comment by AgentAntelope** [comment]
Sorry, totally missed these notifications! I'll have a look asap, should be a day or two? if that's not soon enough, feel free to take it on :)

**Comment by Jameskmonger** [comment]
Nope that's all fine @AgentAntelope - good luck! :fireworks:
